baseURL = "http://example.org/"
languageCode = "en-us"
title = "Alpha Church"

ignoreFiles = [".*"]
disableKinds = ["section","taxonomy","taxonomyTerm","RSS","404","sitemap"]
defaultContentLanguage = "cli"

[outputs]
  home = ["CLI"]

[mediaTypes."text/custom"]
  suffixes = [""]
  delimiter = ""

[outputFormats."CLI"]
  mediaType = "text/custom"
  isHTML = "false"
  baseName = "hugo.log"

[taxonomies]
  tag = "tags"
  preacher = "preachers"
  series = "series"
